name: Terraform Infrastructure and Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Initialize Terraform
      working-directory: terraform/infrastructure
      run: terraform init

    # Untaint the Resource (if needed)
    - name: Untaint iamcredentials.googleapis.com
      working-directory: terraform/infrastructure
      run: |
        terraform state list | grep "google_project_service.required_apis\[\"iamcredentials.googleapis.com\"\]" && \
        terraform untaint google_project_service.required_apis["iamcredentials.googleapis.com"] || echo "Resource not tainted"

    #- name: Import Existing Artifact Registry (if needed)
    #  working-directory: terraform/infrastructure
    #  run: |
    #    terraform import google_artifact_registry_repository.langswarm_repo \
    #      projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.GCP_REGION }}/repositories/langswarm || echo "Already imported or not needed"

    - name: Apply Terraform Plan
      working-directory: terraform/infrastructure
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=${{ secrets.GCP_REGION }}"
          
    - name: Authenticate Docker with Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/langswarm/langswarm-backend:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/langswarm/langswarm-backend:latest

    - name: Build and Push Frontend Docker Image
      run: |
        cd frontend
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/langswarm/langswarm-frontend:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/langswarm/langswarm-frontend:latest

    - name: Initialize Terraform
      working-directory: terraform/serverless
      run: terraform init
      
    - name: Apply Terraform Plan
      working-directory: terraform/serverless
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=${{ secrets.GCP_REGION }}" -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"
